### ISSUE TITLE
Re-encoding to UTF-8 breaks signing

### ISSUE THREAD

**Issue by mubix** [Microsoft/Advanced-Threat-Analytics#1]
As discovered by @mattifestation

Fix: https://twitter.com/mattifestation/status/906252862727921665
`Get-Content .\Advanced-Threat-Analytics.psm1 | Out-File -Encoding ascii .\fixed.psm1`

![ata_fix](https://user-images.githubusercontent.com/679319/30230798-dcd4226c-94b5-11e7-8b5e-f51eed86b4a6.jpg)

**Comment by Javanite** [comment]
This does not fix the larger problem which as to do with how GitHub zips files. To avoid this issue download either from the PS Gallery or use Git Clone. Don't download using the zip file.
