### ISSUE TITLE
Get-ATAStatus not working

### ISSUE THREAD

**Issue by mubix** [Microsoft/Advanced-Threat-Analytics#2]
Getting the following error:
```
Get-ATAStatus : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-ATAStatus
    + CategoryInfo             : InvalidArgument: (:) [Get-ATAStatus], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-ATAStatus
```

**Comment by mubix** [comment]
The other functions work just fine and pulls activity

**Comment by leomatias** [comment]
I have same issue, wasn't this solved yet?

**Comment by Javanite** [comment]
![image](https://user-images.githubusercontent.com/19479604/32793878-0d4cc21a-c91c-11e7-9152-4d7e7f67d3d8.png)

Simply running Get-ATAStatus is not the proper way to use this cmdlet. Please have a look at the help for the cmdlet, you will see that it requires one of the switch parameters. See the attached screenshot.
