### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by hkelley** [Microsoft/Advanced-Threat-Analytics#5]
Is this API documented anywhere?   I have a use case (find all recent new activities/usages for a named user) that the cmdlets won't cover.

The REST API seems pretty easy to access but I can't find a list of methods.

**Comment by Javanite** [comment]
@hkelley The endpoints I am using aren't formally supported or documented, they are simply leveraging the endpoints in the console. ATA does not have a published API, unfortunately, however you might be able to leverage this module to do what you're attempting. You would just use the Get-ATASuspiciousActivity cmdlet and client-side filter the results by the timeframe you care about and the user. 

Unfortunately, the console API's do not support POST method calls where you can retrieve specific users or timeframes, so you have to do a GET, then sort.

**Comment by hkelley** [comment]
Thanks.   It does looks like I can get to what I need via PS:

`
param 
(
      [Parameter(Mandatory = $true)] [string] $targetUser
)

$adUser = Get-ADUser $targetUser

$userEntity =  Get-ATAUniqueEntity -Id $adUser.ObjectGUID.Guid -Profile


$accessedEntities =  @()
$userEntity.AccessedResourceAccountIdToTimeMapping.PSObject.Properties | %{

    $entity = Get-ATAUniqueEntity -Id $_.Name
    $accessedEntities += [pscustomobject] @{
        ResourceName = $entity.SAMNAme
        ResourceDesc = $entity.Description
        ResourceFirstAccessDate = $_.Value
    }
}

$accessedEntities 

`
